### ISSUE TITLE
Allow DEV-19 filtering on MSH-5 (Receiving Application) and MSH-6 (Receiving Facility)

### ISSUE THREAD

**Issue by strentax** [IHE/DEV.PCIM#10]
During the Spring 2023 IHE PCD Face to Face, we discussed the current capabilities of the DEV-19 query. To set up a filter with current specifications, you would need to know the patient's ID or location information. If I just want a feed of "all of my devices" or "all of my devices at this facility", I don't have that option and it'd be nice to have.

**Describe the solution you'd like**
During the DEV-19 query, I should be able to also specify adding a filter criteria to MSH-5 and MSH-6. (this is interesting because I'm sending as MSH-3/4 during the query, but I'd be the receiver on the DEV-52 messages.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bilhar97** [comment]
Would this also allow for specifying the organizationally unique id (OUI) as a filter for "all my devices"? 
For example:
OBX|5||70058^MDC_DEV_PUMP_INFUS_P
CA_VMD^MDC|1.1.0.0|||||||X|||||||1098437^CADD Solis^001A010000000001^EUI-64
The OUI for the late Smiths Medical would be "001A01".
