### ISSUE TITLE
Add error code for DEV-19 not supported by Manager

### ISSUE THREAD

**Issue by eldonmetz** [IHE/DEV.PCIM#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bilhar97** [comment]
If the Manager does not support the DEV-19 message, it should return the following in the Commit level acknowledgment:
MSA-1 = CR (Enhanced mode Commit Reject)
ERR-3 (HL7 Error Code) = 200 (Unsupported Message Type)
ERR-4 (Severity) = E

**Comment by eldonmetz** [comment]
Auto-close didn't work as a # was missing before the issue number. Closing manually.
