### ISSUE TITLE
Review of 14-JULY-2023 PCIM Spec and Foundational spec

### ISSUE THREAD

**Issue by bilhar97** [IHE/DEV.PCIM#46]
I reviewed both documents today (July 17th). My comments:
1.	Appendix A updates: Switch places of DPAC and DPAM in table. Reflects workflow better and matches original PCIM Spec changes.
2.	Appendix A: DPAM description: “…delivers records that match device-patient association queries…” to “..delivers records that match device patient association subscription query filter…”?
3.	Section 7.4 Do we need a use case for updating an existing device-patient association? 
4.	Section 3.19.4.2 Message Semantics: It looks like the original text, rather than the updated test made it into the PCIM Foundational PDF file.
5.	Section 3.19.4.2.1 Trigger Events: Some updated text missing from the PCIM Foundational PDF file.
6.	Table A.1.1-1 Report Device Patient Association: “{“ row: Replace “..for each device…” to “…for the device…”?
7.	Paragraph 760 (in original PCIM spec, carried over into Foundational spec). Is this section still relevant as is?  Not sure  what this means in the context of the new PCIM?
“A device association can be reported as a point-in-time event, in which case a separate disassociate message is not required to delineate the end of the association. Alternatively, the association event message can convey a duration during which the association was in effect. The latter is equivalent to an associate/disassociate message pair and may be preferable for short duration associations (e.g., spot vitals collection).”
8.	Section A.1.2.6 PRT: Change “There will be PRT messages identifying the device, responsible observer…” to “There will be PRT segments identifying the device, responsible observer,….”.
9.	Section A.2.3.2-3 QPD Segment: Update second paragraph “…so that for example, a patient identifier and a device identifier specification…” to “…so that for example, a patient location and a device identifier specification
10.	A.4 Example Messages, Example 2 (Nurse Ratched/McMurphy). First sentence after sample message hints that the unvalidated assertion will be sent to the DPAC (“The Association Manager may then broadcast this information to subscribers…..”).
11.	A.4 Example Message, Example 3: Foundational CP contains an example QPD segment showing a query by PID.3.1.

**Comment by eldonmetz** [comment]
Thank you @bilhar97! I've created a PR with commits for many of these items. 

What is left for discussion after the review of the changes to address the rest:

- 3. Section 7.4 Do we need a use case for updating an existing device-patient association?
- 7. Paragraph 760 (in original PCIM spec, carried over into Foundational spec). Is this section still relevant as is? Not sure what this means in the context of the new PCIM?
“A device association can be reported as a point-in-time event, in which case a separate disassociate message is not required to delineate the end of the association. Alternatively, the association event message can convey a duration during which the association was in effect. The latter is equivalent to an associate/disassociate message pair and may be preferable for short duration associations (e.g., spot vitals collection).”
