### ISSUE TITLE
Merge CP #4 (error codes) into CP #1 (foundational)

### ISSUE THREAD

**Issue by eldonmetz** [IHE/DEV.PCIM#58]
Merge CP #4 text into CP #1, updating sections as necessary due to changes in structure and content in current state of foundational CP.

**Comment by bilhar97** [comment]
Starting on this now.

**Comment by eldonmetz** [comment]
> Starting on this now.

Excellent! I can make time this afternoon to assist if you need it.

**Comment by bilhar97** [comment]
> > Starting on this now.
> 
> Excellent! I can make time this afternoon to assist if you need it.

Thanks. I'll send another message with status when I'm done. This is the only time I can work on this prior to Friday's PCIM meeting (which I may miss, since I'm on vacation this week).

**Comment by bilhar97** [comment]
Pull request available for review.
