### ISSUE TITLE
Review of Latest PCIM Foundational Spec - Comments

### ISSUE THREAD

**Issue by bilhar97** [IHE/DEV.PCIM#73]
I read through the latest PCIM Foundational CP and have a couple of questions (not necessarily issues). I think the doc looks great otherwise.
Questions:
1) Table 3.52.2-1 Actor Roles: “…The Manager must send current associations for all devices…..after a connection is established”. Question: The Manager will always do this when a network connection is established, whether it supports DEV-19 or not? In other words, if a Consumer uses DEV-19 to filter messages, and the Manager supports DEV-19, the Consumer will get DEV-52 messages for all associations when it connects to Manager be default, then get DEV-52 for all filtered associations when it sends the DEV-19 to the Manager?
2) Section 3.52.4.1.1 Trigger Events: “On receipt of the messages, the consumer system checks for valid syntax and …” For points 2 “device is a member of registered device instances and has no conflicting associations” and point 3 “patient is a known person in appropriate status (e.g., admitted)” the Consumer may not know if the patient is admitted or assume the Manager is the source of truth when it comes to patient association conflicts. Should the Consumer override the current patient association in this case and return normal ACK or send NACK to the Manager when this occurs? Or was the association conflict referring to another type of conflict e.g., Consumer knows that the pump is associated with a patient via a PCD-03 (PIV) request at the time the DEV-52 for it arrived?
3) Section A.1.3 Application Acknowledgment. Error codes start at Lower Limit +1. I thought a change was made earlier to have the codes start at Lower Limit.

**Comment by eldonmetz** [comment]
@bilhar97, let's discuss question 1 in our meeting today. I agree some clarification is probably necessary . This is a DEV-52, so the connection is established by the manager to the consumer. This is completely independent of an optional DEV-19 transaction ever being utilized. If the manager does or does not have a filter for that consumer (DEV-19 initiated or preconfigured), then it "must" send the current associations based on that.

**Comment by eldonmetz** [comment]
@bilhar97, I will create a PR for question #2. I think we completely remove the text stating the consumer does any of that validation, the manager does this in concert with the responsible observer!
